SERVER_IP = "localhost"
SERVER_PORT = 5000

CLIENTFILES_DIRECTORY = "./FILESCLIENT/"
CLIENTSCREENSHOT_DIRECTORY = "./FILESCLIENT/screenshots"
CLIENTUNZIP_DIRECTORY = "./FILESCLIENT/unzip"
CLIENTZIP_DIRECTORY = "./FILESCLIENT/zip"


SERVERFILES_DIRECTORY = "./FILESSERVER/"
SERVERSCREENSHOT_DIRECTORY = "./FILESSERVER/screenshots"
SERVERUNZIP_DIRECTORY = "./FILESSERVER/unzip"
SERVERZIP_DIRECTORY = "./FILESSERVER/zip"


ABGABE_DIRECTORY = "/home/student/ABGABE"
