SERVER_IP = "localhost"
SERVER_PORT = 5000

SOURCE_DIRECTORY="/home/waldelf/.life/EXAM" 
SCRIPTS_DIRECTORY="/home/waldelf/.life/EXAM/scripts"


CLIENTFILES_DIRECTORY = "./FILESCLIENT"
CLIENTSCREENSHOT_DIRECTORY = "./FILESCLIENT/screenshots"
CLIENTUNZIP_DIRECTORY = "./FILESCLIENT/unzip"
CLIENTZIP_DIRECTORY = "./FILESCLIENT/zip"
CLIENT_EXAMCONFIG_DIRECTORY = "./FILESCLIENT/EXAMCONFIG"


SERVERFILES_DIRECTORY = "./FILESSERVER"
SERVERSCREENSHOT_DIRECTORY = "./FILESSERVER/screenshots"
SERVERUNZIP_DIRECTORY = "./FILESSERVER/unzip"
SERVERZIP_DIRECTORY = "./FILESSERVER/zip"

SERVER_EXAMCONFIG_DIRECTORY = "./FILESSERVER/EXAMCONFIG"

ABGABE_DIRECTORY = "/home/student/ABGABE"
