# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyCustomWidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.mywidget = QtWidgets.QWidget(Form)
        self.mywidget.setGeometry(QtCore.QRect(70, 10, 145, 94))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mywidget.sizePolicy().hasHeightForWidth())
        self.mywidget.setSizePolicy(sizePolicy)
        self.mywidget.setStyleSheet("border-width: 1px; border-style: solid; border-color: #AAA; margin-top: 4px; margin-left:4px;")
        self.mywidget.setObjectName("mywidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.mywidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(4, 4, 142, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setStyleSheet("padding:0;margin:0;border:0;")
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("LIFE-Dev/life-exam/pixmaps/Test.jpg"))
        self.image.setScaledContents(False)
        self.image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.image.setObjectName("image")
        self.verticalLayout.addWidget(self.image)
        self.info = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info.sizePolicy().hasHeightForWidth())
        self.info.setSizePolicy(sizePolicy)
        self.info.setMinimumSize(QtCore.QSize(122, 18))
        self.info.setMaximumSize(QtCore.QSize(122, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info.setFont(font)
        self.info.setStyleSheet("padding:0;margin:0;border:0;")
        self.info.setAlignment(QtCore.Qt.AlignCenter)
        self.info.setObjectName("info")
        self.verticalLayout.addWidget(self.info)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_icons = QtWidgets.QGridLayout()
        self.gridLayout_icons.setHorizontalSpacing(0)
        self.gridLayout_icons.setVerticalSpacing(1)
        self.gridLayout_icons.setObjectName("gridLayout_icons")
        self.status2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status2.sizePolicy().hasHeightForWidth())
        self.status2.setSizePolicy(sizePolicy)
        self.status2.setStyleSheet("padding:0;margin:0;border:0;")
        self.status2.setText("")
        self.status2.setPixmap(QtGui.QPixmap("LIFE-Dev/life-exam/pixmaps/fileok.png"))
        self.status2.setAlignment(QtCore.Qt.AlignCenter)
        self.status2.setObjectName("status2")
        self.gridLayout_icons.addWidget(self.status2, 1, 0, 1, 1)
        self.status4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status4.sizePolicy().hasHeightForWidth())
        self.status4.setSizePolicy(sizePolicy)
        self.status4.setStyleSheet("padding:0;margin:0;border:0;")
        self.status4.setText("")
        self.status4.setPixmap(QtGui.QPixmap("LIFE-Dev/life-exam/pixmaps/fileok.png"))
        self.status4.setAlignment(QtCore.Qt.AlignCenter)
        self.status4.setObjectName("status4")
        self.gridLayout_icons.addWidget(self.status4, 3, 0, 1, 1)
        self.status1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status1.sizePolicy().hasHeightForWidth())
        self.status1.setSizePolicy(sizePolicy)
        self.status1.setStyleSheet("padding:0;margin:0;border:0;")
        self.status1.setText("")
        self.status1.setPixmap(QtGui.QPixmap("LIFE-Dev/life-exam/pixmaps/fileok.png"))
        self.status1.setAlignment(QtCore.Qt.AlignCenter)
        self.status1.setObjectName("status1")
        self.gridLayout_icons.addWidget(self.status1, 0, 0, 1, 1)
        self.status3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status3.sizePolicy().hasHeightForWidth())
        self.status3.setSizePolicy(sizePolicy)
        self.status3.setStyleSheet("padding:0;margin:0;border:0;")
        self.status3.setText("")
        self.status3.setPixmap(QtGui.QPixmap("LIFE-Dev/life-exam/pixmaps/fileok.png"))
        self.status3.setAlignment(QtCore.Qt.AlignCenter)
        self.status3.setObjectName("status3")
        self.gridLayout_icons.addWidget(self.status3, 2, 0, 1, 1)
        self.status5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status5.sizePolicy().hasHeightForWidth())
        self.status5.setSizePolicy(sizePolicy)
        self.status5.setStyleSheet("padding:0;margin:0;border:0;")
        self.status5.setText("")
        self.status5.setPixmap(QtGui.QPixmap("LIFE-Dev/life-exam/pixmaps/fileok.png"))
        self.status5.setAlignment(QtCore.Qt.AlignCenter)
        self.status5.setObjectName("status5")
        self.gridLayout_icons.addWidget(self.status5, 4, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_icons)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 130, 211, 61))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 200, 211, 61))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(230, 20, 211, 61))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.info.setText(_translate("Form", "TextLabel"))
        self.label.setText(_translate("Form", "Beachte das Margin! nur ob,li. Die HorizontalLayout Größe wird im ui File direkt gesetzt"))
        self.label_2.setText(_translate("Form", "GridLayout für Icons wird im Quellcode zu einem FlowLayout umgewandelt"))
        self.label_3.setText(_translate("Form", "Die Icons sind Platzhalter"))
