version: 1

apps:
   '1':
      - wxmaxima
      - geogebra
   '2':
      - libreOffice writer
      - libreOffice calc
      - only office
      - firefox
      - chrome
   '3':
      - kate
      - brackets
      - kcalc
      - calligra words
      - musescore
      - audacity
