version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(name)s : %(message)s"
    datefmt: "%H:%M:%S"
  default:
    format: "%(asctime)s] [%(levelname)s,%(funcName)s():%(lineno)s] %(message)s"
    datefmt: "%H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: life_exam_server.log
    maxBytes: 1048576 # 1MB
    backupCount: 2
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: default
    filename: life_exam_server_errors.log
    maxBytes: 1048576 # 1MB
    backupCount: 2
    encoding: utf8

loggers:
  twisted:
    level: ERROR
    handlers: [console]
    propagate: no

root:
  level: DEBUG
  handlers: [console, debug_file_handler, error_file_handler]